### ISSUE TITLE
OrangeCrab r0.2.1 no longer enumerating through dfu-util

### ISSUE THREAD

**Issue by biosbob** [orangecrab-fpga/orangecrab-examples#31]
i have a newly-purchased orangecrab board that is no longer enumerating through `dfu-util --list`....  worse, the green power led no longer illuminates when i  power the board through usb; and the continually changing rgb led is basically frozen....

wanting to program the board through jtag, i connected an adafruit ft232h board to the orange crab as follows:

<img width="598" alt="image" src="https://github.com/orangecrab-fpga/orangecrab-examples/assets/57962169/ef274eef-d1dd-421a-9996-3fe5c0c95b22">

i also chose to power the orange crab using 5V taken from the adafruit board....

when i would run `ecpprog -t`, however, all of the ID bytes were 0x0; further attempts to read flash also returned 0x0....

assuming i haven't fried my orangecrab, is there any path to return the board to its original (working) state????

**Comment by gregdavill** [comment]
Hi @biosbob. The LEDs sound like it's a hw fault. If the issue cropped up with general use, you can try contacting groupgets or the distributor where you bought it for an RMA. Alternatively I've got some repaired/tested boards here that I can replace it with too, contact me via email.
